### PR TITLE
Goimports 

### PR DESCRIPTION
**Pull request by erinpentecost**
Added tests for goimports.
Added -i flag to vugufmt to handle goimports. Should this be a different executable altogether (vuguimports)?

#10

### CODE REVIEW

**Comment by bradleypeabody** [comment]
This looks like it bombs in Travis-CI because goimports is not available in the environment. https://api.travis-ci.org/v3/job/516940129/log.txt

Any ideas on how to fix?  If not feasible I would be okay with just making the goimports test require a command line flag for now (so it doesn't run on Travis-CI but can still be invoked manually from the command line).

**Comment by erinpentecost** [comment]
I can make a makefile that handles gofmt/goimports installation and then runs tests, and then call that inside the TravesCI configuration. Sound good?

**Comment by bradleypeabody** [comment]
I'm not a big fan of makefiles, but could be fine if it's specifically for Travis-CI.  But would it not work to just do (and I'm only reading from the [docs here](https://docs.travis-ci.com/user/installing-dependencies/), I have no experience with this, but seems like it would work):

In .travis.yml:
```yaml
before_install:
  - go get golang.org/x/tools/cmd/goimports && go install golang.org/x/tools/cmd/goimports
```

I'm a big fan of reducing tool dependencies wherever possible.  But again, for Travis-CI it doesn't really matter so I don't want to be too picky.  I'm mostly concerned if it affects the experience for other developers using (or to a lesser degree, hacking on) the vugu library; which I don't think this does.

**Comment by erinpentecost** [comment]
Your change to the TravisCI config looks perfect.

**Comment by bradleypeabody** [comment]
Cool, although I'm realizing now I might need to do something to add it to the path.   I'll give it a shot.

**Comment by bradleypeabody** [comment]
Yay, it's working.

**Pull request merged**
