### PR TITLE
Vugufmt

### PR DESCRIPTION
**Pull request by erinpentecost**
This is a port from erinpentecost/vugufmt to bring the code into the main vugu repo.
It brings in a lot of code from Go's html package, which has been modified and hidden under /vugufmt/internal.

### CODE REVIEW

**Comment by erinpentecost** [comment]
#31

**Comment by erinpentecost** [comment]
#9

**Comment by bradleypeabody** [comment]
Thanks for all the work you've put in on this.  One quick note is can you move `github.com/vugu/vugu/vugufmt/internal` to `github.com/vugu/vugu/internal`? (this way the top level vugu code generator can get at your htmlx package and can use its line number functionality)

And otherwise I'm having a bit of trouble getting it to work.  Hopefully it's something simple.

Here's what I'm trying:

I create [demo-site-path]/demo.vugu as:
```html
<div>
    <h1>This is a test</h1>
        <p>Some text here.</p>
</div>

<style>
.test { background: green; }
</style>

<script type="application/x-go">
func Blah() int { return 0 }
</script>
```

With your PR checked out I `go install ./cmd/vugufmt`, it creates the executable and it's in my path. (I checked to make sure it's the latest, based on the code from this PR - commit 04a5a3e).

Then from [demo-site-path] I do: `vugufmt demo.vugu`.  It outputs the same file to stdout with no changes.   Trying with `-d` gives no output, and with `-w` does not appear to change the file at all.

Any ideas?

**Comment by bradleypeabody** [comment]
Okay sorry, my bad - I was looking at that func and expecting it to be broken into three lines.  It is in fact working on the Go code.

Does it do any indentation adjustment on the HTML perchance?

**Comment by erinpentecost** [comment]
Sure thing, I should have some time today to move stuff around.

Unfortunately, this version does not format HTML. Building up the DOM tree and then rendering it back out just wasn't reliable. This version does do some simple error checking on the HTML though and reports where in the file the error is. I figured HTML formatting could be a future change.

**Comment by bradleypeabody** [comment]
Okay awesome, makes sense.

I will try to spend some time this evening reviewing the code in more detail and will look out for an update to the PR with that internal folder change.  Should be no problem to merge it into master very soon.

**Comment by erinpentecost** [comment]
The format function will return an unedited version of the input if there was an error. The second return value will be non-nil if there's an error, and it includes location fields in the source input as well as an error message describing the issue. This makes it so we won't accidentally blow away the file if there's an error by placing the error info in the same return value.

**Comment by bradleypeabody** [comment]
I'm merging this in now.  Great work!

**Pull request merged**
